### ISSUE TITLE
衝突判定のEnterとExitの実装案

### ISSUE THREAD

**Issue by para7** [mak1a/SivComponent#1]
### とりあえず仮想関数を作る
それはそう

# ゲームエンジン全体
現フレーム判定のためのint型を作ります
エンジンのメインループのたびにインクリメントさせるやつ

# 衝突判定マスターみたいなコンポーネントがあったはずなので改造します

### 前フレームで衝突したオブジェクト一覧のforward_listを作る
パフォーマンス的にたぶんforward_listがベスト
いやわからん　ワンチャンmapの方が検索は早いし全体が早くなるかもしれん　でも再構築かかりやすい気もするし何十個も重ならないからlistでいいと思う
このforward_listはゲームオブジェクトを直接ではない。int型とゲームオブジェクトのポインタをセットにして管理する

### 関数呼び出し構造忘れたけど、最終的に各コンポーネントの衝突関数が呼ばれるわけですが（たぶんforで全コンポーネントの関数を呼ぶよう回してるはず）その直前でチェックを入れる
forward_listを線形探索してあるかないか調べます。なかったらEnterを呼び出す。そしてlistに追加(衝突する数なんてたかが知れてるので平気)
**ここ重要なので忘れるな**listはint型を持ってるので、そこに現在のフレームIDを保存しておく

### Exit処理専用関数を作る

現在のIDとListのIDを比較し、一致しなかったらExitを呼ぶ→Listから除外する関数

# どこだか忘れたけど衝突判定エンジンの動作開始してる場所あたりに処理を書く

衝突判定エンジンが終了→Exit判定開始　の流れ

衝突エンジンが終了したあとに全オブジェクトをforで回してさっき作ったExit処理専用関数を呼ぶ

でたぶんできる

**Comment by mak1a** [comment]
実装完了しました！ご協力ありがとうございます！
