### ISSUE TITLE
フレームカウンターの共通化案

### ISSUE THREAD

**Issue by para7** [mak1a/SivComponent#2]
global.cpp

namespace ComponentEngine::Global{
    

static int frameCount = 0;

void Update(){
    ++frameCount;
}

int FrameCount(){
    return frameCount;
}

}

global.hpp

namespace ComponentEngine::Global{
    
int FrameCount();
}

SceneManager.cpp

Main()
{
    Global::Update();
}

currentID = Global::FrameCount();

**Comment by mak1a** [comment]
修正完了しました。ご協力ありがとうございました！
